### ISSUE TITLE
No hardcode left in hecate.core.base

### ISSUE THREAD

**Issue by a5kin** [a5kin/hecate#20]
The main goal of this step is to rid of all the hardcoded parts in core.base module. In the course of action, related parts in other modules will be rewritten as well, expanding framework functionality.

**TODO list:**
- [x] Implement simple dtype calculation algorithm using declared properties
- [x] Make _elementwise_kernel args dynamic / using dtype
- [x] Rewrite CUDA parts involving state getting in order to make them dynamic
- [x] Make CellularAutomaton.buffers dynamic
- [x] Implement color effects module
- [x] Make fade_in, fade_out and smooth_factor dynamic
- [x] Make _translate_code to actually run functions and get same result
- [x] Make defines dynamic
- [x] Make index_to_coord dynamic
- [x] Make pack_state dynamic
- [x] Implement Render / RenderPlain class
- [x] Make render params and its functions (zoom, move, etc.) to be generated by Render class

**Comment by a5kin** [comment]
Framework is fully dynamic now. We were not only got rid off all hardcoded parts, but actually complete all features we planned to include in the first release. And even more, the framework already has a support for multidimensional models and multiple properties per CA state.

At the next iteration, we will focus on first release preparations. Probably, some bugfixes will also follow.
